export const OWNER_LIGHT_COLORS = {
  surface: "#FFFFFF",
  surfaceAlt: "#F0FAFA",
  header: "#1A7A7A",
  primary: "#1A7A7A",
  primaryLight: "#1A9E9E",
  accent: "#E8A020",
  accentLight: "#F0C060",
  background: "#E8F5F5",
  backgroundAlt: "#FFFFFF",
  text: "#102A2A",
  muted: "#5F7474",
  border: "#CFE8E8",
  danger: "#D94848",
};

export const OWNER_DARK_COLORS = {
  surface: "#182525",
  surfaceAlt: "#203434",
  header: "#0F3F3F",
  primary: "#62D0D0",
  primaryLight: "#7FE0E0",
  accent: "#F0C060",
  accentLight: "#F7D88B",
  background: "#0D1717",
  backgroundAlt: "#122020",
  text: "#F2FFFF",
  muted: "#A6BDBD",
  border: "#2C4A4A",
  danger: "#FF7A7A",
};

export const getOwnerColors = (theme = "light") =>
  theme === "dark" ? OWNER_DARK_COLORS : OWNER_LIGHT_COLORS;

export const TRANSLATIONS = {
  en: {
    home: "Home",
    bookings: "Bookings",
    wallet: "Wallet",
    profile: "Profile",
    myProfile: "My Profile",
    personalInformation: "Personal Information",
    addresses: "Addresses",
    paymentMethods: "Payment Methods",
    referEarn: "Refer & Earn",
    notificationSettings: "Notification Settings",
    helpSupport: "Help & Support",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    logout: "Logout",
    editProfile: "Edit Profile",
    saveDetails: "Save Details",
    saveAddress: "Save Address",
    fullName: "Full Name",
    mobileNumber: "Mobile Number",
    societyName: "Society Name",
    flatNo: "Flat / House Number",
    address: "Address",
    appSettings: "App Settings",
    myAccount: "My Account",
    location: "Location",
    searchServices: "Search services...",
    allServices: "All Services",
    browseByCategory: "Browse by category",
    welcomeSignin: "Welcome. Your mobile is verified. Please sign in.",
  },
  te: {
    home: "హోమ్",
    bookings: "బుకింగ్స్",
    wallet: "వాలెట్",
    profile: "ప్రొఫైల్",
    myProfile: "నా ప్రొఫైల్",
    personalInformation: "వ్యక్తిగత సమాచారం",
    addresses: "చిరునామాలు",
    paymentMethods: "చెల్లింపు పద్ధతులు",
    referEarn: "రిఫర్ & ఎర్న్",
    notificationSettings: "నోటిఫికేషన్ సెట్టింగ్స్",
    helpSupport: "సహాయం",
    language: "భాష",
    theme: "థీమ్",
    light: "లైట్",
    dark: "డార్క్",
    logout: "లాగ్ అవుట్",
    editProfile: "ప్రొఫైల్ మార్చండి",
    saveDetails: "వివరాలు సేవ్ చేయండి",
    saveAddress: "చిరునామా సేవ్ చేయండి",
    fullName: "పూర్తి పేరు",
    mobileNumber: "మొబైల్ నంబర్",
    societyName: "సొసైటీ పేరు",
    flatNo: "ఫ్లాట్ / ఇల్లు నంబర్",
    address: "చిరునామా",
    appSettings: "యాప్ సెట్టింగ్స్",
    myAccount: "నా ఖాతా",
    location: "ప్రాంతం",
    searchServices: "సేవలు వెతకండి...",
    allServices: "అన్ని సేవలు",
    browseByCategory: "వర్గం ద్వారా చూడండి",
    welcomeSignin: "స్వాగతం. మీ మొబైల్ ధృవీకరించబడింది. సైన్ ఇన్ చేయండి.",
  },
  hi: {
    home: "होम",
    bookings: "बुकिंग",
    wallet: "वॉलेट",
    profile: "प्रोफाइल",
    myProfile: "मेरी प्रोफाइल",
    personalInformation: "व्यक्तिगत जानकारी",
    addresses: "पते",
    paymentMethods: "पेमेंट तरीके",
    referEarn: "रेफर और कमाएं",
    notificationSettings: "नोटिफिकेशन सेटिंग्स",
    helpSupport: "सहायता",
    language: "भाषा",
    theme: "थीम",
    light: "लाइट",
    dark: "डार्क",
    logout: "लॉग आउट",
    editProfile: "प्रोफाइल एडिट करें",
    saveDetails: "विवरण सेव करें",
    saveAddress: "पता सेव करें",
    fullName: "पूरा नाम",
    mobileNumber: "मोबाइल नंबर",
    societyName: "सोसाइटी नाम",
    flatNo: "फ्लैट / घर नंबर",
    address: "पता",
    appSettings: "ऐप सेटिंग्स",
    myAccount: "मेरा खाता",
    location: "स्थान",
    searchServices: "सेवाएं खोजें...",
    allServices: "सभी सेवाएं",
    browseByCategory: "श्रेणी से देखें",
    welcomeSignin: "स्वागत है. आपका मोबाइल सत्यापित है. कृपया साइन इन करें.",
  },
};

const EXTRA_TRANSLATIONS = {
  en: {
    myBookings: "My Bookings",
    upcoming: "Upcoming",
    completed: "Completed",
    cancelled: "Cancelled",
    loadingBookings: "Loading bookings...",
    serverIssue: "Server issue",
    retry: "Retry",
    noBookingsPrefix: "No",
    noBookingsSuffix: "bookings",
    bookingsAppearHere: "Bookings you create will appear here.",
    bookingId: "Booking ID",
    startOtp: "Start OTP",
    showOtp: "Show OTP",
    details: "Details",
    rebook: "Rebook",
    new: "New",
    bookAgainSaveMore: "Book Again, Save More!",
    nextBookingOffer: "Get up to 20% OFF on your next booking",
    viewOffers: "View Offers",
    myWallet: "My Wallet",
    walletBalance: "Wallet Balance",
    addMoney: "Add Money",
    sendMoney: "Send Money",
    transactionHistory: "Transaction History",
    recentTransactions: "Recent Transactions",
    refresh: "Refresh",
    noTransactionsFound: "No transactions found",
    inviteEarn: "Invite & Earn",
    inviteFriends: "Invite your friends and get up to Rs 500",
    inviteNow: "Invite Now",
    enterAmount: "Enter amount",
    continueToPayment: "Continue to Payment",
    cancel: "Cancel",
    receiverMobileNumber: "Receiver mobile number",
    noServicesFound: "No services found",
    bookNow: "Book Now",
    "category.household": "Household",
    "category.repairs": "Repairs",
    "category.personalCare": "Personal Care",
    "category.healthcare": "Healthcare",
    "category.transport": "Transport",
    "category.petLifestyle": "Pet & Lifestyle",
    "category.personalServices": "Personal Services",
    "category.techSupport": "Tech & Support",
    "category.events": "Events",
    "category.outdoor": "Outdoor & Safety",
    "service.deepCleaning": "Deep Cleaning",
    "service.homeChef": "Home Chef",
    "service.maid": "Maid",
    "service.laundry": "Laundry",
    "service.waterTankCleaning": "Water Tank Cleaning",
    "service.poolCleaning": "Pool Cleaning",
    "service.ironingService": "Ironing Service",
    "service.sofaCleaning": "Sofa / Carpet Cleaning",
    "service.electrician": "Electrician",
    "service.plumber": "Plumber",
    "service.acRepair": "AC Repair",
    "service.handyman": "Handyman",
    "service.carpenter": "Carpenter",
    "service.painting": "Painting",
    "service.furnitureAssembly": "Furniture Assembly",
    "service.homeRenovation": "Home Renovation",
    "service.tiling": "Tiling",
    "service.roofing": "Roofing",
    "service.glassFitting": "Glass / Window Fitting",
    "service.waterproofing": "Waterproofing",
    "service.salonAtHome": "Salon at Home",
    "service.beautician": "Beautician",
    "service.massageTherapy": "Massage Therapy",
    "service.mehendi": "Mehendi Artist",
    "service.makeupArtist": "Makeup Artist",
    "service.doctor": "Doctor Visit",
    "service.homeNurse": "Home Nurse",
    "service.physiotherapy": "Physiotherapy",
    "service.labTestAtHome": "Lab Test at Home",
    "service.elderCare": "Elder Care",
    "service.babyCare": "Baby Care / Nanny",
    "service.driver": "Driver",
    "service.carWash": "Car Wash",
    "service.moving": "Shifting / Moving",
    "service.petWalking": "Pet Training",
    "service.fitnessTrainer": "Fitness / Yoga",
    "service.tutor": "Tutor",
    "service.dietitian": "Dietitian / Nutritionist",
    "service.wifiSetup": "WiFi Setup",
    "service.cctvInstallation": "CCTV Installation",
    "service.security": "Security Services",
    "service.computerRepair": "Computer / Laptop Repair",
    "service.birthdayDecor": "Birthday Decorations",
    "service.eventPhotography": "Event Photography",
    "service.cateringServices": "Catering Services",
    "service.partyPlanner": "Party Planner",
    "service.tentHouse": "Tent House / Mandap",
    "service.dj": "DJ / Sound System",
    "service.gardening": "Gardening",
    "service.pestControl": "Pest Control",
    "service.sewageTreatment": "Sewage Treatment",
    "service.borewellService": "Borewell Service",
    "service.solarInstallation": "Solar Panel Installation",
  },
  te: {
    myBookings: "నా బుకింగ్స్",
    upcoming: "రాబోయేవి",
    completed: "పూర్తయినవి",
    cancelled: "రద్దు",
    loadingBookings: "బుకింగ్స్ లోడ్ అవుతున్నాయి...",
    serverIssue: "సర్వర్ సమస్య",
    retry: "మళ్లీ ప్రయత్నించండి",
    noBookingsPrefix: "బుకింగ్స్ లేవు",
    noBookingsSuffix: "",
    bookingsAppearHere: "మీరు చేసే బుకింగ్స్ ఇక్కడ కనిపిస్తాయి.",
    bookingId: "బుకింగ్ ఐడి",
    startOtp: "ప్రారంభ OTP",
    showOtp: "OTP చూపు",
    details: "వివరాలు",
    rebook: "మళ్లీ బుక్ చేయండి",
    new: "కొత్తది",
    bookAgainSaveMore: "మళ్లీ బుక్ చేసి ఆదా చేయండి!",
    nextBookingOffer: "మీ తదుపరి బుకింగ్ పై 20% వరకు ఆఫర్",
    viewOffers: "ఆఫర్లు చూడండి",
    myWallet: "నా వాలెట్",
    walletBalance: "వాలెట్ బ్యాలెన్స్",
    addMoney: "డబ్బు జోడించండి",
    sendMoney: "డబ్బు పంపండి",
    transactionHistory: "లావాదేవీ చరిత్ర",
    recentTransactions: "తాజా లావాదేవీలు",
    refresh: "రిఫ్రెష్",
    noTransactionsFound: "లావాదేవీలు లేవు",
    inviteEarn: "ఆహ్వానించి సంపాదించండి",
    inviteFriends: "మీ స్నేహితులను ఆహ్వానించి Rs 500 వరకు పొందండి",
    inviteNow: "ఇప్పుడు ఆహ్వానించండి",
    enterAmount: "మొత్తం నమోదు చేయండి",
    continueToPayment: "చెల్లింపుకు కొనసాగండి",
    cancel: "రద్దు",
    receiverMobileNumber: "రిసీవర్ మొబైల్ నంబర్",
    noServicesFound: "సేవలు కనబడలేదు",
    bookNow: "ఇప్పుడే బుక్ చేయండి",
    "category.household": "ఇంటి పనులు",
    "category.repairs": "మరమ్మత్తులు",
    "category.personalCare": "వ్యక్తిగత సంరక్షణ",
    "category.healthcare": "ఆరోగ్య సేవలు",
    "category.transport": "రవాణా",
    "category.petLifestyle": "పెట్ & లైఫ్ స్టైల్",
    "category.personalServices": "వ్యక్తిగత సేవలు",
    "category.techSupport": "టెక్ & సపోర్ట్",
    "category.events": "ఈవెంట్స్",
    "category.outdoor": "అవుట్ డోర్ & భద్రత",
    "service.deepCleaning": "డీప్ క్లీనింగ్",
    "service.homeChef": "హోమ్ చెఫ్",
    "service.maid": "మెయిడ్",
    "service.laundry": "లాండ్రీ",
    "service.waterTankCleaning": "వాటర్ ట్యాంక్ క్లీనింగ్",
    "service.poolCleaning": "పూల్ క్లీనింగ్",
    "service.ironingService": "ఇస్త్రీ సేవ",
    "service.sofaCleaning": "సోఫా / కార్పెట్ క్లీనింగ్",
    "service.electrician": "ఎలక్ట్రీషియన్",
    "service.plumber": "ప్లంబర్",
    "service.acRepair": "ఏసీ రిపేర్",
    "service.handyman": "హ్యాండీమ్యాన్",
    "service.carpenter": "కార్పెంటర్",
    "service.painting": "పెయింటింగ్",
    "service.furnitureAssembly": "ఫర్నిచర్ అసెంబ్లీ",
    "service.homeRenovation": "హోమ్ రెనోవేషన్",
    "service.tiling": "టైలింగ్",
    "service.roofing": "రూఫింగ్",
    "service.glassFitting": "గ్లాస్ / విండో ఫిట్టింగ్",
    "service.waterproofing": "వాటర్ ప్రూఫింగ్",
    "service.salonAtHome": "ఇంట్లో సలూన్",
    "service.beautician": "బ్యూటీషియన్",
    "service.massageTherapy": "మసాజ్ థెరపీ",
    "service.mehendi": "మెహెంది ఆర్టిస్ట్",
    "service.makeupArtist": "మేకప్ ఆర్టిస్ట్",
    "service.doctor": "డాక్టర్ విజిట్",
    "service.homeNurse": "హోమ్ నర్స్",
    "service.physiotherapy": "ఫిజియోథెరపీ",
    "service.labTestAtHome": "ఇంట్లో ల్యాబ్ టెస్ట్",
    "service.elderCare": "వృద్ధుల సంరక్షణ",
    "service.babyCare": "బేబీ కేర్ / నానీ",
    "service.driver": "డ్రైవర్",
    "service.carWash": "కార్ వాష్",
    "service.moving": "షిఫ్టింగ్ / మూవింగ్",
    "service.petWalking": "పెట్ ట్రైనింగ్",
    "service.fitnessTrainer": "ఫిట్నెస్ / యోగా",
    "service.tutor": "ట్యూటర్",
    "service.dietitian": "డైటీషియన్ / న్యూట్రిషనిస్ట్",
    "service.wifiSetup": "వైఫై సెటప్",
    "service.cctvInstallation": "సీసీటీవీ ఇన్‌స్టాలేషన్",
    "service.security": "సెక్యూరిటీ సేవలు",
    "service.computerRepair": "కంప్యూటర్ / ల్యాప్‌టాప్ రిపేర్",
    "service.birthdayDecor": "పుట్టినరోజు అలంకరణలు",
    "service.eventPhotography": "ఈవెంట్ ఫోటోగ్రఫీ",
    "service.cateringServices": "కేటరింగ్ సేవలు",
    "service.partyPlanner": "పార్టీ ప్లానర్",
    "service.tentHouse": "టెంట్ హౌస్ / మండపం",
    "service.dj": "డీజే / సౌండ్ సిస్టమ్",
    "service.gardening": "గార్డెనింగ్",
    "service.pestControl": "పెస్ట్ కంట్రోల్",
    "service.sewageTreatment": "సీవేజ్ ట్రీట్మెంట్",
    "service.borewellService": "బోర్వెల్ సేవ",
    "service.solarInstallation": "సోలార్ ప్యానెల్ ఇన్‌స్టాలేషన్",
  },
  hi: {
    myBookings: "मेरी बुकिंग",
    upcoming: "आने वाली",
    completed: "पूरी हुई",
    cancelled: "रद्द",
    loadingBookings: "बुकिंग लोड हो रही हैं...",
    serverIssue: "सर्वर समस्या",
    retry: "फिर कोशिश करें",
    noBookingsPrefix: "कोई",
    noBookingsSuffix: "बुकिंग नहीं",
    bookingsAppearHere: "आपकी बनाई बुकिंग यहां दिखाई देंगी.",
    bookingId: "बुकिंग आईडी",
    startOtp: "स्टार्ट OTP",
    showOtp: "OTP दिखाएं",
    details: "विवरण",
    rebook: "फिर बुक करें",
    new: "नई",
    bookAgainSaveMore: "फिर बुक करें, ज्यादा बचाएं!",
    nextBookingOffer: "अगली बुकिंग पर 20% तक छूट पाएं",
    viewOffers: "ऑफर देखें",
    myWallet: "मेरा वॉलेट",
    walletBalance: "वॉलेट बैलेंस",
    addMoney: "पैसे जोड़ें",
    sendMoney: "पैसे भेजें",
    transactionHistory: "लेन-देन इतिहास",
    recentTransactions: "हाल के लेन-देन",
    refresh: "रिफ्रेश",
    noTransactionsFound: "कोई लेन-देन नहीं मिला",
    inviteEarn: "आमंत्रित करें और कमाएं",
    inviteFriends: "दोस्तों को आमंत्रित करें और Rs 500 तक पाएं",
    inviteNow: "अभी आमंत्रित करें",
    enterAmount: "राशि दर्ज करें",
    continueToPayment: "पेमेंट जारी रखें",
    cancel: "रद्द करें",
    receiverMobileNumber: "रिसीवर मोबाइल नंबर",
    noServicesFound: "कोई सेवा नहीं मिली",
    bookNow: "अभी बुक करें",
    "category.household": "घरेलू काम",
    "category.repairs": "मरम्मत",
    "category.personalCare": "व्यक्तिगत देखभाल",
    "category.healthcare": "स्वास्थ्य सेवाएं",
    "category.transport": "यातायात",
    "category.petLifestyle": "पेट और लाइफस्टाइल",
    "category.personalServices": "व्यक्तिगत सेवाएं",
    "category.techSupport": "टेक और सपोर्ट",
    "category.events": "इवेंट्स",
    "category.outdoor": "आउटडोर और सुरक्षा",
    "service.deepCleaning": "डीप क्लीनिंग",
    "service.homeChef": "होम शेफ",
    "service.maid": "मेड",
    "service.laundry": "लॉन्ड्री",
    "service.waterTankCleaning": "वॉटर टैंक क्लीनिंग",
    "service.poolCleaning": "पूल क्लीनिंग",
    "service.ironingService": "इस्त्री सेवा",
    "service.sofaCleaning": "सोफा / कार्पेट क्लीनिंग",
    "service.electrician": "इलेक्ट्रिशियन",
    "service.plumber": "प्लंबर",
    "service.acRepair": "एसी रिपेयर",
    "service.handyman": "हैंडिमैन",
    "service.carpenter": "कारपेंटर",
    "service.painting": "पेंटिंग",
    "service.furnitureAssembly": "फर्नीचर असेंबली",
    "service.homeRenovation": "होम रेनोवेशन",
    "service.tiling": "टाइलिंग",
    "service.roofing": "रूफिंग",
    "service.glassFitting": "ग्लास / विंडो फिटिंग",
    "service.waterproofing": "वॉटरप्रूफिंग",
    "service.salonAtHome": "घर पर सैलून",
    "service.beautician": "ब्यूटीशियन",
    "service.massageTherapy": "मसाज थेरेपी",
    "service.mehendi": "मेहंदी आर्टिस्ट",
    "service.makeupArtist": "मेकअप आर्टिस्ट",
    "service.doctor": "डॉक्टर विजिट",
    "service.homeNurse": "होम नर्स",
    "service.physiotherapy": "फिजियोथेरेपी",
    "service.labTestAtHome": "घर पर लैब टेस्ट",
    "service.elderCare": "एल्डर केयर",
    "service.babyCare": "बेबी केयर / नैनी",
    "service.driver": "ड्राइवर",
    "service.carWash": "कार वॉश",
    "service.moving": "शिफ्टिंग / मूविंग",
    "service.petWalking": "पेट ट्रेनिंग",
    "service.fitnessTrainer": "फिटनेस / योग",
    "service.tutor": "ट्यूटर",
    "service.dietitian": "डाइटीशियन / न्यूट्रिशनिस्ट",
    "service.wifiSetup": "वाईफाई सेटअप",
    "service.cctvInstallation": "सीसीटीवी इंस्टॉलेशन",
    "service.security": "सिक्योरिटी सेवाएं",
    "service.computerRepair": "कंप्यूटर / लैपटॉप रिपेयर",
    "service.birthdayDecor": "जन्मदिन सजावट",
    "service.eventPhotography": "इवेंट फोटोग्राफी",
    "service.cateringServices": "कैटरिंग सेवाएं",
    "service.partyPlanner": "पार्टी प्लानर",
    "service.tentHouse": "टेंट हाउस / मंडप",
    "service.dj": "डीजे / साउंड सिस्टम",
    "service.gardening": "गार्डनिंग",
    "service.pestControl": "पेस्ट कंट्रोल",
    "service.sewageTreatment": "सीवेज ट्रीटमेंट",
    "service.borewellService": "बोरवेल सेवा",
    "service.solarInstallation": "सोलर पैनल इंस्टॉलेशन",
  },
};

export const t = (language, key) =>
  EXTRA_TRANSLATIONS[language]?.[key] ||
  EXTRA_TRANSLATIONS.en[key] ||
  TRANSLATIONS[language]?.[key] ||
  TRANSLATIONS.en[key] ||
  key;
