import { useEffect, useState } from 'react';
import { providerApi } from '../api/providerApi';

export const WORKER_LIGHT_COLORS = {
  bg: '#F8F9FC',
  card: '#FFFFFF',
  header: '#1E1B4B',
  primary: '#4F46E5',
  success: '#22C55E',
  successSoft: '#DCFCE7',
  text: '#1E1B4B',
  muted: '#6B7280',
  border: '#E5E7EB',
  soft: '#EEF2FF',
};

export const WORKER_DARK_COLORS = {
  bg: '#1E1B4B',
  card: '#172A40',
  text: '#EEF2FF',
  muted: '#B8C7D9',
  border: '#284057',
  soft: '#20364F',
  header: '#1E1B4B',
  primary: '#4F46E5',
  success: '#22C55E',
  successSoft: '#DCFCE7',
};

export const getWorkerColors = (theme = 'light') =>
  theme === 'dark' ? WORKER_DARK_COLORS : WORKER_LIGHT_COLORS;

const en = {
  home: 'Home',
  bookings: 'Bookings',
  earnings: 'Earnings',
  profile: 'Profile',
  myProfile: 'My Profile',
  notifications: 'Notifications',
  schedule: 'My Schedule',
  availability: 'Availability',
  language: 'Language',
  theme: 'Theme',
  light: 'Light',
  dark: 'Dark',
  servicesOffered: 'Services Offered',
  addServices: 'Add services',
  done: 'Done',
  today: 'Today',
  completed: 'Completed',
  rating: 'Rating',
  online: 'Online',
  offline: 'Offline',
  todaysEarnings: "Today's Earnings",
  viewEarnings: 'View Earnings',
  youAreOnline: 'You are Online',
  youAreOffline: 'You are Offline',
  receiveRequests: 'You will receive new booking requests',
  noRequests: 'You will not receive booking requests',
  todaysOverview: "Today's Overview",
  newJobRequests: 'New Job Requests',
  viewAll: 'View All',
  noNewJobRequests: 'No new job requests',
  acceptedJobsAppear: 'Accepted jobs will appear in your bookings.',
  currentBooking: 'Current Booking',
  noActiveBooking: 'No active booking',
  activeBookingHint: 'Accepted or started work appears here.',
  myBookings: 'My Bookings',
  refresh: 'Refresh',
  all: 'All',
  upcoming: 'Upcoming',
  inProgress: 'In Progress',
  cancelled: 'Cancelled',
  loadingBookings: 'Loading bookings...',
  serverIssue: 'Server issue',
  retry: 'Retry',
  owner: 'Owner',
  customer: 'Customer',
  place: 'Place',
  addressNotAdded: 'Address not added',
  totalEarnings: 'Total Earnings',
  thisMonth: 'This Month',
  earningsSummary: 'Earnings Summary',
  completedServices: 'Completed Services',
  lastMonth: 'Last Month',
  recentTransactions: 'Recent Transactions',
  markAllRead: 'Mark all as read',
  workingDays: 'Working Days',
  workingHours: 'Working Hours',
  startTime: 'Start Time',
  endTime: 'End Time',
  breakTime: 'Break Time',
  optional: 'Optional',
  addBreak: 'Add a break during your shift',
  setWorkingHours: 'Set your working hours and days',
  saveSchedule: 'Save Schedule',
  saving: 'Saving...',
  saved: 'Saved!',
  availabilitySet: 'Availability Set!',
  scheduleActive: 'This schedule is active. Edit anytime to make changes.',
  selectTime: 'Select Time',
  selectStartTime: 'Select Start Time',
  selectEndTime: 'Select End Time',
  breakStartsAt: 'Break Starts At',
  breakEndsAt: 'Break Ends At',
  personalInformation: 'Personal Information',
  documents: 'Documents',
  verified: 'Verified',
  bankDetails: 'Bank Details',
  changePassword: 'Change Password',
  profileCompletion: 'Profile Completion',
  verifiedWorker: 'Verified Worker',
  logOut: 'Log Out',
};

const te = {
  ...en,
  home: 'హోమ్',
  bookings: 'బుకింగ్స్',
  earnings: 'ఆదాయం',
  profile: 'ప్రొఫైల్',
  myProfile: 'నా ప్రొఫైల్',
  notifications: 'నోటిఫికేషన్లు',
  schedule: 'నా షెడ్యూల్',
  availability: 'లభ్యత',
  language: 'భాష',
  theme: 'థీమ్',
  light: 'లైట్',
  dark: 'డార్క్',
  servicesOffered: 'అందించే సేవలు',
  addServices: 'సేవలు జోడించండి',
  done: 'పూర్తి',
  today: 'ఈ రోజు',
  completed: 'పూర్తయ్యాయి',
  rating: 'రేటింగ్',
  online: 'ఆన్‌లైన్',
  offline: 'ఆఫ్‌లైన్',
  todaysEarnings: 'ఈరోజు ఆదాయం',
  viewEarnings: 'ఆదాయం చూడండి',
  youAreOnline: 'మీరు ఆన్‌లైన్‌లో ఉన్నారు',
  youAreOffline: 'మీరు ఆఫ్‌లైన్‌లో ఉన్నారు',
  receiveRequests: 'మీకు కొత్త బుకింగ్ అభ్యర్థనలు వస్తాయి',
  noRequests: 'మీకు బుకింగ్ అభ్యర్థనలు రావు',
  todaysOverview: 'ఈరోజు అవలోకనం',
  newJobRequests: 'కొత్త పని అభ్యర్థనలు',
  viewAll: 'అన్నీ చూడండి',
  noNewJobRequests: 'కొత్త పని అభ్యర్థనలు లేవు',
  acceptedJobsAppear: 'అంగీకరించిన పనులు మీ బుకింగ్స్‌లో కనిపిస్తాయి.',
  currentBooking: 'ప్రస్తుత బుకింగ్',
  noActiveBooking: 'యాక్టివ్ బుకింగ్ లేదు',
  activeBookingHint: 'అంగీకరించిన లేదా ప్రారంభించిన పని ఇక్కడ కనిపిస్తుంది.',
  myBookings: 'నా బుకింగ్స్',
  refresh: 'రిఫ్రెష్',
  all: 'అన్నీ',
  upcoming: 'రాబోయేవి',
  inProgress: 'ప్రగతిలో',
  cancelled: 'రద్దు',
  loadingBookings: 'బుకింగ్స్ లోడ్ అవుతున్నాయి...',
  serverIssue: 'సర్వర్ సమస్య',
  retry: 'మళ్లీ ప్రయత్నించండి',
  owner: 'ఓనర్',
  customer: 'కస్టమర్',
  place: 'స్థలం',
  addressNotAdded: 'చిరునామా జోడించలేదు',
  totalEarnings: 'మొత్తం ఆదాయం',
  thisMonth: 'ఈ నెల',
  earningsSummary: 'ఆదాయం సారాంశం',
  completedServices: 'పూర్తైన సేవలు',
  lastMonth: 'గత నెల',
  recentTransactions: 'ఇటీవలి లావాదేవీలు',
  markAllRead: 'అన్నీ చదివినట్లుగా గుర్తించండి',
  workingDays: 'పని రోజులు',
  workingHours: 'పని గంటలు',
  startTime: 'ప్రారంభ సమయం',
  endTime: 'ముగింపు సమయం',
  breakTime: 'విరామ సమయం',
  optional: 'ఐచ్ఛికం',
  addBreak: 'మీ షిఫ్ట్‌లో విరామం జోడించండి',
  setWorkingHours: 'మీ పని గంటలు మరియు రోజులను సెట్ చేయండి',
  saveSchedule: 'షెడ్యూల్ సేవ్ చేయండి',
  saving: 'సేవ్ అవుతోంది...',
  saved: 'సేవ్ అయింది!',
  availabilitySet: 'లభ్యత సెట్ అయింది!',
  scheduleActive: 'ఈ షెడ్యూల్ యాక్టివ్‌గా ఉంది. మార్పులకు ఎప్పుడైనా ఎడిట్ చేయండి.',
  selectTime: 'సమయం ఎంచుకోండి',
  selectStartTime: 'ప్రారంభ సమయం ఎంచుకోండి',
  selectEndTime: 'ముగింపు సమయం ఎంచుకోండి',
  breakStartsAt: 'విరామం ప్రారంభం',
  breakEndsAt: 'విరామం ముగింపు',
  personalInformation: 'వ్యక్తిగత సమాచారం',
  documents: 'పత్రాలు',
  verified: 'ధృవీకరించబడింది',
  bankDetails: 'బ్యాంక్ వివరాలు',
  changePassword: 'పాస్‌వర్డ్ మార్చండి',
  profileCompletion: 'ప్రొఫైల్ పూర్తి',
  verifiedWorker: 'ధృవీకరించిన వర్కర్',
  logOut: 'లాగ్ అవుట్',
};

const hi = {
  ...en,
  home: 'होम',
  bookings: 'बुकिंग्स',
  earnings: 'कमाई',
  profile: 'प्रोफाइल',
  myProfile: 'मेरी प्रोफाइल',
  notifications: 'नोटिफिकेशन',
  schedule: 'मेरा शेड्यूल',
  availability: 'उपलब्धता',
  language: 'भाषा',
  theme: 'थीम',
  light: 'लाइट',
  dark: 'डार्क',
  servicesOffered: 'दी जाने वाली सेवाएं',
  addServices: 'सेवाएं जोड़ें',
  done: 'पूर्ण',
  today: 'आज',
  completed: 'पूर्ण',
  rating: 'रेटिंग',
  online: 'ऑनलाइन',
  offline: 'ऑफलाइन',
  todaysEarnings: 'आज की कमाई',
  viewEarnings: 'कमाई देखें',
  youAreOnline: 'आप ऑनलाइन हैं',
  youAreOffline: 'आप ऑफलाइन हैं',
  receiveRequests: 'आपको नई बुकिंग रिक्वेस्ट मिलेंगी',
  noRequests: 'आपको बुकिंग रिक्वेस्ट नहीं मिलेंगी',
  todaysOverview: 'आज का सारांश',
  newJobRequests: 'नई जॉब रिक्वेस्ट',
  viewAll: 'सभी देखें',
  noNewJobRequests: 'नई जॉब रिक्वेस्ट नहीं हैं',
  acceptedJobsAppear: 'स्वीकार की गई जॉब आपकी बुकिंग में दिखेगी.',
  currentBooking: 'मौजूदा बुकिंग',
  noActiveBooking: 'कोई सक्रिय बुकिंग नहीं',
  activeBookingHint: 'स्वीकार या शुरू किया काम यहां दिखेगा.',
  myBookings: 'मेरी बुकिंग्स',
  refresh: 'रिफ्रेश',
  all: 'सभी',
  upcoming: 'आने वाली',
  inProgress: 'प्रगति में',
  cancelled: 'रद्द',
  loadingBookings: 'बुकिंग्स लोड हो रही हैं...',
  serverIssue: 'सर्वर समस्या',
  retry: 'फिर कोशिश करें',
  owner: 'ओनर',
  customer: 'कस्टमर',
  place: 'स्थान',
  addressNotAdded: 'पता नहीं जोड़ा गया',
  totalEarnings: 'कुल कमाई',
  thisMonth: 'इस महीने',
  earningsSummary: 'कमाई सारांश',
  completedServices: 'पूर्ण सेवाएं',
  lastMonth: 'पिछला महीना',
  recentTransactions: 'हाल की लेनदेन',
  markAllRead: 'सभी को पढ़ा हुआ करें',
  workingDays: 'काम के दिन',
  workingHours: 'काम के घंटे',
  startTime: 'शुरू समय',
  endTime: 'समाप्ति समय',
  breakTime: 'ब्रेक समय',
  optional: 'वैकल्पिक',
  addBreak: 'अपनी शिफ्ट में ब्रेक जोड़ें',
  setWorkingHours: 'अपने काम के घंटे और दिन सेट करें',
  saveSchedule: 'शेड्यूल सेव करें',
  saving: 'सेव हो रहा है...',
  saved: 'सेव हो गया!',
  availabilitySet: 'उपलब्धता सेट हुई!',
  scheduleActive: 'यह शेड्यूल सक्रिय है. बदलाव के लिए कभी भी एडिट करें.',
  selectTime: 'समय चुनें',
  selectStartTime: 'शुरू समय चुनें',
  selectEndTime: 'समाप्ति समय चुनें',
  breakStartsAt: 'ब्रेक शुरू',
  breakEndsAt: 'ब्रेक समाप्त',
  personalInformation: 'व्यक्तिगत जानकारी',
  documents: 'दस्तावेज',
  verified: 'सत्यापित',
  bankDetails: 'बैंक विवरण',
  changePassword: 'पासवर्ड बदलें',
  profileCompletion: 'प्रोफाइल पूर्णता',
  verifiedWorker: 'सत्यापित वर्कर',
  logOut: 'लॉग आउट',
};

export const WORKER_TRANSLATIONS = { en, te, hi };

export const wt = (language, key) =>
  WORKER_TRANSLATIONS[language]?.[key] || WORKER_TRANSLATIONS.en[key] || key;

export const useWorkerPreferences = () => {
  const [preferences, setPreferences] = useState({ language: 'en', theme: 'light' });

  useEffect(() => {
    let mounted = true;
    providerApi.getProviderPreferences().then((stored) => {
      if (mounted) setPreferences(stored);
    });
    const unsubscribe = providerApi.subscribeProviderPreferences?.((nextPreferences) => {
      setPreferences(nextPreferences);
    });
    return () => {
      mounted = false;
      if (unsubscribe) unsubscribe();
    };
  }, []);

  return preferences;
};

export const DEFAULT_WORKER_AVAILABILITY = {
  isOnline: true,
  selectedDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  startTime: '09:00 AM',
  endTime: '08:00 PM',
  breakEnabled: false,
  breakStart: '01:00 PM',
  breakEnd: '02:00 PM',
};
